name: GitHub CI

on:
  pull_request:
  push:
  schedule:
    - cron: 0 0 * * 0

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  validate_vtcs:
    strategy:
      matrix:
        version: ["60lts", "73", "74", "75"]
    runs-on: ubuntu-latest
    steps :
      - uses: actions/checkout@v4
      - name: install varnish and test
        run: |
          set -ex
          cat << -EOF > /tmp/pref
               Package: *
               Pin: origin "packagecloud.io"
               Pin-Priority: 999
          EOF
          varnishtest *.vtc

