name: GitHub CI

on:
  pull_request:
  push:
  schedule:
    - cron: 0 0 * * 0

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  validate_vtcs:
    strategy:
      matrix:
        version: ["60lts", "73", "74", "75"]
    runs-on: ubuntu-latest
    steps :
      - uses: actions/checkout@v4
      - name: install varnish and test
        run: |
          set -ex
          cat << EOF > /tmp/pref
          Package: *
          Pin: origin "packagecloud.io"
          Pin-Priority: 999
          EOF
          sudo mv /tmp/pref /etc/apt/preferences.d/varnish
          curl -s https://packagecloud.io/install/repositories/varnishcache/varnish${{ matrix.version }}/script.deb.sh | sudo bash
          sudo apt-get install -y varnish


          # basic-003.vtc needs user interaction
          varnishtest basic-003.vtc &
          curl -v $(ss -plunt | awk '/varnishtest/ {print $5; exit}')
          wait
          rm basic-003.vtc

          # "fix" basic-004.vtc
          sed -i 's/^\s*false/true/' basic-004.vtc
          varnishtest *.vtc
